FROM ubuntu 


#RUN apt-get --yes -qq update 
#RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata
#RUN apt-get --yes -qq update 
#RUN apt-get --yes -qq install build-essential  
#RUN apt-get --yes -qq install gfortran gcc g++  
#RUN apt-get --yes -qq install openmpi-bin libopenmpi-dev  
#RUN apt-get --yes -qq install cmake 
#RUN apt-get --yes -qq clean
#RUN rm -rf /var/lib/apt/lists/*

WORKDIR /WORKING_DIRECTORY
