name: Docker Image CI

on: [push, workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      
    steps:
    - name: OS 
      run: uname -a   
      
    - name: Dowloading repository ... 
      uses: actions/checkout@v2
      
    - name : Info ...
      run : | 
        #mkdir BUILD 
        #cp COMPILER.sh BUILD 
        ls -la  
        #ls -la BUILD 
        pwd 

    - name: Build Docker ... 
      run: |
        docker build . --file Dockerfile.ci 
   
    
    - name: Executing Docker ...  
      if: success()
      run: |
      
        echo "[DOCKER] BUILDING ..."
        
        IMAGE_NAME=i01a
        CONTAINER_NAME=c01a
        
        docker build . --file Dockerfile.ci -t $IMAGE_NAME
        IMAGE_ID=$(docker images --filter=reference=$IMAGE_NAME --format "{{.ID}}") 
        echo "IMAGE_ID:", $IMAGE_ID
        
        
        echo "[DOCKER] CREATING ..." 
        
        docker run \
          --name ${CONTAINER_NAME} \
          --volume ${{ github.workspace }}:/home \
          --workdir /home \
          --rm -i ${IMAGE_NAME} pwd

        docker run \
          --name ${CONTAINER_NAME} \
          --volume ${{ github.workspace }}:/home \
          --workdir /home \
          --rm -i ${IMAGE_NAME} bash COMPILER.sh 

        docker run \
          --name ${CONTAINER_NAME} \
          --volume ${{ github.workspace }}:/home \
          --workdir /home \
          --rm -i ${IMAGE_NAME} ls BUILD 
        
        echo "[DOCKER] DONE!"         
        
        
