name: Docker Image CI

on: [push, workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      
    steps:
    - name: OS 
      run: uname -a   
      
    - name: Dowloading repository ... 
      uses: actions/checkout@v2
      
    - name : Info ...
      run : | 
        
        mkdir BUILD 
        cp COMPILER.sh BUILD 
        ls -la  
        ls -la BUILD 
        pwd 

#    - name: Build the Docker image
#      run: |
#        docker build . --file Dockerfile.ci 
   
    
    
        
        
