name: docker_ci3

on: [workflow_dispatch] # push 

jobs:

  build:

    runs-on: ubuntu-latest
    
    strategy:
      max-parallel: 4
      
    steps:
    - name: OS SYSTEM INFO ... 
      run: |
        uname -a   
        pwd
        ls 
      
    - name: CHECKING OUT REPO ...
      uses: actions/checkout@v4
            
    - name: SETUP PROCESS ... 
      run: |
        SETUP_SYSTEM() 
        {
          #apt-get --yes -qq update 
          #DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata
          sudo apt-get --yes -qq update 
          sudo apt-get --yes -qq install build-essential  
          sudo apt-get --yes -qq install gfortran gcc g++  
          sudo apt-get --yes -qq install openmpi-bin libopenmpi-dev  
          sudo apt-get --yes -qq install cmake 
          #apt-get --yes -qq clean
          #rm -rf /var/lib/apt/lists/*
        }
        SETUP_SYSTEM 

    - name: BUILDING PROCESS ... 
      run: |
        CMAKE()
        {  
          cmake ../SRC  \
                -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/EXECS01 \
                -DPARAVIEW_BUILD_QT_GUI=OFF \
                -DCMAKE_CXX_FLAGS=-fpermissive \
                -DCMAKE_CXX_COMPILER=mpicxx  \
                -DCMAKE_C_COMPILER=mpicc \
                -DCMAKE_Fortran_COMPILER=mpif90 \
                -DPARAVIEW_USE_ICE_T=OFF \
                -DPARAVIEW_USE_MPI=ON \
                -DBUILD_SHARED_LIBS=OFF \
                -DVTK_Group_ParaViewRendering=OFF \
                -DVTK_USE_X=OFF \
                -DVTK_OPENGL_HAS_OSMESA=OFF \
                -DVTK_OPENGL_HAS_EGL=OFF \
                -DModule_vtkIOExport=OFF \
                -DVTK_BUILD_ALL_MODULES_FOR_TESTS=OFF \
                -DVTK_Group_Rendering=OFF \
                -DVTK_Group_StandAlone=OFF \
                -DVTK_Group_MPI=ON \
                -DModule_vtkCommonCore=ON \
                -DModule_vtkFiltersGeneral=ON \
                -DVTK_RENDERING_BACKEND=None \
                -DPARAVIEW_ENABLE_VTK_MODULES_AS_NEEDED=FALSE \
                -DModule_vtkVTKm=ON \
                -DModule_vtkAcceleratorsVTKm=ON \
                -DModule_vtkPVVTKExtensionsDefault=ON \
                -DPARAVIEW_ENABLE_COMMANDLINE_TOOLS=OFF \
                -DPARAVIEW_CURRENT_CS_MODULES= 
                
        }
      
        mkdir BUILD 
        cd BUILD 
        CMAKE
        
        make -j4 
        ls -la 
        pwd 
        
        make install
        ls -la 


    - name: upload-artifact
      if: success() 
      uses: actions/upload-artifact@v4
      with:
        name: ArtifactName3
        path: ${{ github.workspace }}/EXECS01 

    - env :
          GH_TOKEN: ${{ secrets.TOKEN4 }} 
      if: success() 
      run : |
        source "$GITHUB_WORKSPACE/Tools/tools.sh"
        release_with_artifact '${{ github.repository }}' '${{ github.actor }}' "TagX.Y.Z" ${{ github.workspace }}/EXECS01
    
             
