name: docker_ci3

on: [push, workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest
    
    strategy:
      max-parallel: 4
      
    steps:
    - name: OS SYSTEM INFO ... 
      run: |
        uname -a   
        pwd
        ls 
      
    - name: CHECKING OUT REPO ...
      uses: actions/checkout@v4
            
    - name: BUILDING PROCESS ... 
      run: |
        SETUP_SYSTEM() 
        {
          #apt-get --yes -qq update 
          #DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata
          sudo apt-get --yes -qq update 
          sudo apt-get --yes -qq install build-essential  
          sudo apt-get --yes -qq install gfortran gcc g++  
          sudo apt-get --yes -qq install openmpi-bin libopenmpi-dev  
          sudo apt-get --yes -qq install cmake 
          #apt-get --yes -qq clean
          #rm -rf /var/lib/apt/lists/*
        }

        SETUP_SYSTEM 


          
        
             
