name: Docker Image CI

on: [push, workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      
    steps:
    - name: OS 
      run: uname -a   
      
    - name: Dowloading repository ... 
      uses: actions/checkout@v2
      
    - name : Info ...
      run : | 
        pwd 
        ls -la 
      
#    - name: Build the Docker image
#      run: |
#        docker build . --file Dockerfile.ci 
   
    
    
        
        
