name: Docker Image CI

on: [push, workflow_dispatch]

env:
  CONTAINER_NAME: c01a

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      
    steps:
    - name: OS 
      run: | 
        ls -la 
        pwd 
        uname -a   
      
    - name: Dowloading repository ... 
      uses: actions/checkout@v2
      
    
    - name: Executing Docker ...  
      if: success()
      run: |
      
        echo "[DOCKER] BUILDING ..."
        
        IMAGE_NAME=i01a:$GITHUB_SHA
        
        docker build . \
        --file Dockerfile.ci \
        --tag $IMAGE_NAME
        
        IMAGE_ID=$(docker images --filter=reference=$IMAGE_NAME --format "{{.ID}}") 
        echo "IMAGE_ID:", $IMAGE_ID
                
        echo "[DOCKER] CREATING ..." 
        
        docker run \
          --name ${CONTAINER_NAME} \
          --volume ${{ github.workspace }}:/home \
          --workdir /home \
          --rm -i ${IMAGE_NAME} pwd

        docker run \
          --name ${CONTAINER_NAME} \
          --volume ${{ github.workspace }}:/home \
          --workdir /home \
          --rm -i ${IMAGE_NAME} bash COMPILER.sh 

        docker run \
          --name ${CONTAINER_NAME} \
          --volume ${{ github.workspace }}:/home \
          --workdir /home \
          --rm -i ${IMAGE_NAME} ls BUILD 


        echo "[DOCKER] PUSHING ..." 
        
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA
        

        echo "[DOCKER] DONE!! :) "    


#    - name: Login to Docker Hub ... 
#      uses: actions-hub/docker/login@master
#      env:
#        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }} # jmake
#        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}    # https://hub.docker.com/settings/security >> Access Tokens 
#        DOCKER_REPOSITORY: ${{ secrets.DOCKER_HUB_TOKEN }}  # decafpv560
        
    - name: Pushing the Docker Image ...
      run: |
      
        echo "IMAGE_NAME:",${IMAGE_NAME}
        
        #echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io
        
        #docker build . --file Dockerfile.swig --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA
        
        #docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA       
        
        
        
