name: Docker Image CI

on: [push, workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest
    
    strategy:
      max-parallel: 4
      
    steps:
    - name: OS SYSTEM INFO ... 
      run: |
        uname -a   
        pwd
        ls 
      
    - name: CHECKING OUT REPO ...
      uses: actions/checkout@v2
            
    - name: BUILDING PROCESS WITH DOCKER ... 
      uses: addnab/docker-run-action@v3
      with:
        image: ubuntu 
        shell: bash
        options: -v ${{ github.workspace }}:/tmp 
        run: |
          ls -la  
          ls -la /home 
        
             
