name: Docker Image CI

on: [push, workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      
    steps:
    - name: OS 
      run: uname -a   
      
    - name: Dowloading repository ... 
      uses: actions/checkout@v2
      
    - name : Info ...
      run : | 
        
        mkdir BUILD 
        cp COMPILER.sh BUILD 
        ls -la  
        ls -la BUILD 
        pwd 

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile.ci 
   
    
    - name: Executing Docker image 
      if: success()
      run: |
        echo "[DOCKER] BUILDING ..."
        IMAGE_NAME=gh01
        CONTAINER_NAME=container01
        docker build . --file Dockerfile.ci -t $IMAGE_NAME:1.0 
        docker images
        
        echo "[DOCKER] CREATING ..." 
        CONTAINER_ID=$(docker create ${IMAGE_NAME}:1.0 --volume ${PWD}:/WORKING_DIRECTORY/ --name ${CONTAINER_NAME})
        #docker start ${CONTAINER_ID} 
        docker run --rm --name ${CONTAINER_NAME} 
        
        
        echo "[DOCKER] EXECUTING ..."  
        #docker cp ${CONTAINER_ID}:/home/jovyan/work/from_docker.ipynb ./
        #docker run -v ${PWD}:/BUILD/ ${CONTAINER_ID}
        #docker start ${CONTAINER_ID} 
        #docker exec ${CONTAINER_ID} ls -la /WORKING_DIRECTORY 
        
        docker rm -v $CONTAINER_ID
        
        echo "[DOCKER] DONE!"         
        
        
